services:
  
  ps-postgres:
    image: ankane/pgvector
    env_file: 
      - ./.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 30s
      retries: 5
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    restart: unless-stopped
    container_name: ps-postgres
    ports:
     - 5432:5432
    networks:
     - ps-network

networks:
  ps-network:
    driver: bridge